### ISSUE TITLE
dtsm install failed with --remote option

### ISSUE THREAD

**Issue by vvakame** [vvakame/dtsm#8]
```
$ dtsm --remote git@github.com:vvakame/atom-dts-generator.git --ref ae77e903a207b23d4c3207fabade7200a1bce266 install atom.d.ts --save
Error: Command failed: /bin/sh -c git --git-dir=/Users/vvakame/.dtsm/git/github.com/vvakame/atom-dts-generator show ae77e903a207b23d4c3207fabade7200a1bce266:typings/es6-promise/es6-promise.d.ts
fatal: Path 'typings/es6-promise/es6-promise.d.ts' exists on disk, but not in 'ae77e903a207b23d4c3207fabade7200a1bce266'.

    at ChildProcess.exithandler (child_process.js:685:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:953:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1020:5)
```

**Comment by vvakame** [comment]
or

```
{
  "repos": [
    {
      "url": "https://github.com/borisyankov/DefinitelyTyped.git",
      "ref": "master"
    }
  ],
  "path": "typings",
  "bundle": "typings/bundle.d.ts",
  "dependencies": {
    "atom/atom.d.ts": {
      "ref": "ae77e903a207b23d4c3207fabade7200a1bce266",
      "repo": "git@github.com:vvakame/atom-dts-generator.git",
      "path": "atom.d.ts"
    },
    "node/node.d.ts": {
      "ref": "a834d5f001fb96998a6587343ecccf45fdfbcb6d"
    },
    "es6-promise/es6-promise.d.ts": {
      "ref": "a834d5f001fb96998a6587343ecccf45fdfbcb6d"
    },
    "jasmine/jasmine.d.ts": {
      "ref": "a834d5f001fb96998a6587343ecccf45fdfbcb6d"
    },
    "atom.d.ts": {
      "repo": "git@github.com:vvakame/atom-dts-generator.git",
      "ref": "ae77e903a207b23d4c3207fabade7200a1bce266"
    }
  }
}
```

**Comment by vvakame** [comment]
or 

```
{
  "repos": [
    {
      "url": "https://github.com/borisyankov/DefinitelyTyped.git",
      "ref": "master"
    }
  ],
  "path": "typings",
  "bundle": "typings/bundle.d.ts",
  "dependencies": {
    "node/node.d.ts": {
      "ref": "a834d5f001fb96998a6587343ecccf45fdfbcb6d"
    },
    "es6-promise/es6-promise.d.ts": {
      "ref": "a834d5f001fb96998a6587343ecccf45fdfbcb6d"
    },
    "jasmine/jasmine.d.ts": {
      "ref": "a834d5f001fb96998a6587343ecccf45fdfbcb6d"
    },
    "atom/atom.d.ts": {
      "ref": "b355dbf1e4f909e90920fd4f6447ff35a00e1e40",
      "repo": "git@github.com:vvakame/atom-dts-generator.git",
      "path": "atom.d.ts"
    }
  }
}
```

```
node/node.d.ts borisyankov/DefinitelyTyped#a834d5

es6-promise/es6-promise.d.ts borisyankov/DefinitelyTyped#a834d5

jasmine/jasmine.d.ts borisyankov/DefinitelyTyped#a834d5

atom/atom.d.ts vakame/atom-dts-generator#b355db
└── atom/atom-generate.d.ts
```

vakame?
